-- AT Money Agent USSD automation intentionally NOT seeded.
--
-- The original *110# menu mappings drafted for this migration have not yet
-- been validated against the live screen text of an AT Money Agent SIM.
--
-- This matters because global ussd_flows are usable by every agent and the
-- table defaults is_active to TRUE. Seeding the draft mappings here would
-- therefore enable unverified automation in production.
--
-- Keep migration 053 as an ordered no-op so later migrations can proceed
-- safely. After live AT Money Agent SIM validation, add a NEW migration with
-- the verified flows. Do not retrofit 053 after it has been applied.
--
-- Draft menu paths retained for validation reference:
--
-- Deposit:
--   *110# -> 1 Agent Transaction -> 1 Deposit
--   -> phone -> amount -> PIN
--
-- Normal Wallet Balance:
--   *110# -> 6 -> 1 -> 1 -> PIN
--
-- Cash-In Commission Balance:
--   *110# -> 6 -> 6 -> 1 -> PIN
--
-- Cash-Out Commission Balance:
--   *110# -> 6 -> 1 -> 2 -> PIN
--
-- Agent to Agent:
--   *110# -> 1 -> 4 -> 1
--   -> phone -> amount -> 1 confirm -> PIN
--
-- Intentional no-op.
SELECT 1;
